permalink: /:year/:month/:day/:title
plugins:
  - jekyll_sqlite
  - jekyll-datapage-generator

sqlite:
  - data: pictures-unknown
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=0;
  - data: pictures-2015
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2015;
  - data: pictures-2016
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2016;
  - data: pictures-2017
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2017;
  - data: pictures-2018
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2018;
  - data: pictures-2019
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2019;
  - data: pictures-2020
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2020;
  - data: pictures-2021
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2021;
  - data: pictures-2022
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2022;
  - data: pictures-2023
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2023;
  - data: pictures-2024
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2024;
  - data: pictures-2025
    file: _db/yip.db
    query: SELECT * FROM pictures INNER JOIN years ON pictures.year = years.year WHERE pictures.year=2025;

page_gen:
  - data: pictures-unknown
    page_data_prefix: pictures
    dir: photos
    template: picture
    name: filename
  - data: pictures-2015
    page_data_prefix: pictures
    dir: photos/2015
    template: picture
    name: filename
  - data: pictures-2016
    page_data_prefix: pictures
    dir: photos/2016
    template: picture
    name: filename
  - data: pictures-2017
    page_data_prefix: pictures
    dir: photos/2017
    template: picture
    name: filename
  - data: pictures-2018
    page_data_prefix: pictures
    dir: photos/2018
    template: picture
    name: filename
  - data: pictures-2019
    page_data_prefix: pictures
    dir: photos/2019
    template: picture
    name: filename
  - data: pictures-2020
    page_data_prefix: pictures
    dir: photos/2020
    template: picture
    name: filename
  - data: pictures-2021
    page_data_prefix: pictures
    dir: photos/2021
    template: picture
    name: filename
  - data: pictures-2022
    page_data_prefix: pictures
    dir: photos/2022
    template: picture
    name: filename
  - data: pictures-2023
    page_data_prefix: pictures
    dir: photos/2023
    template: picture
    name: filename
  - data: pictures-2024
    page_data_prefix: pictures
    dir: photos/2024
    template: picture
    name: filename
  - data: pictures-2025
    page_data_prefix: pictures
    dir: photos/2025
    template: picture
    name: filename
sass:
  style: compressed
  sass_dir: _assets
exclude:
  - 'bin'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Rakefile'
  - 'README.md'
  - 'vendor'
# host: 0.0.0.0
